# Generated by Django 5.2.7 on 2025-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('local_encontrado', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('data_encontrado', models.DateField()),
                ('status', models.CharField(default='Pendente', max_length=20)),
            ],
        ),
    ]
