# Generated by Django 5.2.7 on 2025-10-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_item_foto_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='local_encontrado',
            field=models.CharField(max_length=100, verbose_name='Local Encontrado'),
        ),
        migrations.AlterField(
            model_name='item',
            name='responsavel',
            field=models.CharField(max_length=100, verbose_name='Responsável'),
        ),
    ]
