# Generated by Django 5.2.7 on 2025-10-30 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_item_categoria_alter_item_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Devolvido', 'Devolvido'), ('Descartado', 'Descartado')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=200, verbose_name='Nome do Solicitante')),
                ('contato_solicitante', models.CharField(max_length=200, verbose_name='Contato (Telefone/Email)')),
                ('data_solicitacao', models.DateField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('descricao_item_perdido', models.TextField(verbose_name='Descrição do Item Perdido')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Finalizado', 'Finalizado'), ('Não Encontrado', 'Não Encontrado')], default='Pendente', max_length=20, verbose_name='Status da Solicitação')),
                ('item_encontrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to='sistema.item', verbose_name='Item Encontrado (Linkar)')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
