# Generated by Django 5.2.7 on 2025-10-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_item_status_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
