# Generated by Django 5.2.7 on 2025-10-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_solicitacao_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='id_item',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='id_solicitacao',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
