# Generated by Django 5.2.7 on 2025-10-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_remove_item_id_remove_solicitacao_id_item_id_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_itens/'),
        ),
    ]
