# Generated by Django 5.2.7 on 2025-10-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_item_options_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
